"""Workflow data models for the LEAM desktop application."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

ACTIVE_STEP_STATUSES = {
    "idle",
    "running",
    "success",
    "issues",
    "blocked_by_upstream",
    "rerun_required",
    "stale",
    "error",
}


@dataclass
class AttachmentRef:
    """A user-controlled file attached to a workflow step."""

    id: str
    name: str
    path: str
    kind: str
    enabled: bool = True
    editable: bool = False
    origin: str = "user"

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "AttachmentRef":
        return cls(
            id=str(payload.get("id") or ""),
            name=str(payload.get("name") or ""),
            path=str(payload.get("path") or ""),
            kind=str(payload.get("kind") or "text"),
            enabled=bool(payload.get("enabled", True)),
            editable=bool(payload.get("editable", False)),
            origin=str(payload.get("origin") or "user"),
        )


@dataclass
class ArtifactRef:
    """A generated artifact produced by one workflow step."""

    id: str
    step_id: str
    label: str
    path: str
    kind: str
    enabled: bool = True
    created_at: Optional[str] = None

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "ArtifactRef":
        return cls(
            id=str(payload.get("id") or ""),
            step_id=str(payload.get("step_id") or ""),
            label=str(payload.get("label") or ""),
            path=str(payload.get("path") or ""),
            kind=str(payload.get("kind") or "text"),
            enabled=bool(payload.get("enabled", True)),
            created_at=payload.get("created_at"),
        )


@dataclass
class IssueRefill:
    """A routed issue generated by `check_solid` for one upstream step."""

    id: str
    source_step_id: str
    target_step_id: str
    category: str
    severity: str
    message: str
    issue_path: Optional[str] = None
    solid: Optional[str] = None
    inserted_text: str = ""

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "IssueRefill":
        return cls(
            id=str(payload.get("id") or ""),
            source_step_id=str(payload.get("source_step_id") or ""),
            target_step_id=str(payload.get("target_step_id") or ""),
            category=str(payload.get("category") or "alignment"),
            severity=str(payload.get("severity") or "error"),
            message=str(payload.get("message") or ""),
            issue_path=payload.get("issue_path"),
            solid=payload.get("solid"),
            inserted_text=str(payload.get("inserted_text") or ""),
        )


@dataclass
class StepResult:
    """Structured result from one step runner invocation."""

    status: str
    artifact_ids: List[str] = field(default_factory=list)
    primary_artifact_id: Optional[str] = None
    preview_text: str = ""
    logs: List[str] = field(default_factory=list)
    error: str = ""
    raw_payload: Dict[str, Any] = field(default_factory=dict)


@dataclass
class WorkflowStepDefinition:
    """Immutable definition for one step in the desktop workflow."""

    id: str
    title: str
    step_type: str
    system_files: List[str] = field(default_factory=list)
    upstream_step_ids: List[str] = field(default_factory=list)
    default_selected_outputs: Dict[str, List[str]] = field(default_factory=dict)
    is_optional: bool = False
    settings: Dict[str, Any] = field(default_factory=dict)


@dataclass
class WorkflowStepState:
    """Mutable state for one workflow step."""

    status: str = "idle"
    description: str = ""
    refill_notes: str = ""
    attachments: List[AttachmentRef] = field(default_factory=list)
    selected_artifact_ids: List[str] = field(default_factory=list)
    artifact_ids: List[str] = field(default_factory=list)
    issues: List[IssueRefill] = field(default_factory=list)
    raw_issues: List[Dict[str, Any]] = field(default_factory=list)
    logs: List[str] = field(default_factory=list)
    last_error: str = ""
    last_run_at: Optional[str] = None
    run_count: int = 0
    settings: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "WorkflowStepState":
        return cls(
            status=str(payload.get("status") or "idle"),
            description=str(payload.get("description") or ""),
            refill_notes=str(payload.get("refill_notes") or ""),
            attachments=[
                AttachmentRef.from_dict(item)
                for item in payload.get("attachments", []) or []
                if isinstance(item, dict)
            ],
            selected_artifact_ids=[
                str(item)
                for item in payload.get("selected_artifact_ids", []) or []
            ],
            artifact_ids=[
                str(item) for item in payload.get("artifact_ids", []) or []
            ],
            issues=[
                IssueRefill.from_dict(item)
                for item in payload.get("issues", []) or []
                if isinstance(item, dict)
            ],
            raw_issues=[
                item for item in payload.get("raw_issues", []) or []
                if isinstance(item, dict)
            ],
            logs=[str(item) for item in payload.get("logs", []) or []],
            last_error=str(payload.get("last_error") or ""),
            last_run_at=payload.get("last_run_at"),
            run_count=int(payload.get("run_count") or 0),
            settings=dict(payload.get("settings") or {}),
        )


@dataclass
class WorkflowSession:
    """Top-level serializable desktop session."""

    version: int = 1
    title: str = "Untitled Session"
    template: str = "strong_description"
    workspace_dir: str = ""
    session_file: Optional[str] = None
    steps: Dict[str, WorkflowStepState] = field(default_factory=dict)
    artifacts: Dict[str, ArtifactRef] = field(default_factory=dict)
    issues: List[IssueRefill] = field(default_factory=list)
    flags: Dict[str, Any] = field(default_factory=dict)
    status: str = "draft"
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "WorkflowSession":
        return cls(
            version=int(payload.get("version") or 1),
            title=str(payload.get("title") or "Untitled Session"),
            template=str(payload.get("template") or "strong_description"),
            workspace_dir=str(payload.get("workspace_dir") or ""),
            session_file=payload.get("session_file"),
            steps={
                str(key): WorkflowStepState.from_dict(value)
                for key, value in (payload.get("steps") or {}).items()
                if isinstance(value, dict)
            },
            artifacts={
                str(key): ArtifactRef.from_dict(value)
                for key, value in (payload.get("artifacts") or {}).items()
                if isinstance(value, dict)
            },
            issues=[
                IssueRefill.from_dict(item)
                for item in payload.get("issues", []) or []
                if isinstance(item, dict)
            ],
            flags=dict(payload.get("flags") or {}),
            status=str(payload.get("status") or "draft"),
            created_at=payload.get("created_at"),
            updated_at=payload.get("updated_at"),
        )
